### ISSUE TITLE
cofused with bacteria genome

### ISSUE THREAD

**Issue by Achuan-2** [linsalrob/PhageHosts#4]
I want to know where 2698 bacteria genome origin from？

**Comment by Achuan-2** [comment]
part of them are phage host ，but others are what？What is the method of selection？

**Comment by linsalrob** [comment]
The 2,698 bacterial genomes were all the bacterial genomes available in NCBI in 2015 when we did the work. At that time the file was `ftp://ftp.ncbi.nih.gov/refseq/release/bacteria/bacteria.*.fna.gz`.

Nowadays, there are many, many more bacterial genomes available!

**Comment by Achuan-2** [comment]
Got it！ thanks a lot
